# Generated by Django 5.1 on 2024-12-03 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Citas',
            fields=[
                ('idcita', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('idpaciente', models.CharField(max_length=100)),
                ('idmedico', models.CharField(max_length=100)),
                ('fechacita', models.CharField(max_length=100)),
                ('horacita', models.CharField(max_length=100)),
                ('motivo', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
            ],
        ),
    ]
